add giphy pluging
TaimaTask/Giphy_Search pull request #2
Opened 2021-06-20 12:09 UTC by TaimaTask

2021-06-20 12:48 UTC, bqaddumi requested changes

2021-06-20 12:48 UTC, bqaddumi commented on css/styles.css
> +}
format the code

2021-06-20 12:48 UTC, bqaddumi commented on css/styles.css
> +  background-position: 10px 12px; /* Position the search icon */
remove comments

2021-06-20 12:48 UTC, bqaddumi commented on css/styles.css
> +  background-position: 10px 12px; /* Position the search icon */
Why is this needed?

2021-06-20 12:48 UTC, bqaddumi commented on css/styles.css
> +  padding-left: -10px;
why `-10` ? can you change it to optimal, please?

2021-06-20 12:48 UTC, bqaddumi commented on javaScript/js.js
> +let page=1;
nice!

2021-06-20 12:48 UTC, bqaddumi commented on javaScript/js.js
> +let gifButton = document.getElementById("gifButton");// Get the button that opens the modal
remove comment

2021-06-20 12:48 UTC, bqaddumi commented on javaScript/js.js
> +    gifs=content.data;
nice, you stored the data in array

2021-06-20 12:48 UTC, bqaddumi commented on javaScript/js.js
> +}
format your code

2021-06-21 06:31 UTC, merged

2021-06-21 06:44 UTC, TaimaTask commented on css/styles.css
> +  background-position: 10px 12px; /* Position the search icon */
line 51:add search icon on the background of the search text input 
line 52: set the position of the icon inside the search input.

2021-06-21 06:44 UTC, TaimaTask commented on css/styles.css
> +  padding-left: -10px;
for negative value to move the element into left here I can resolve it but 
on the gifView style, I can't because it affect on gif view on the modal, this way resolve my problem with spaces on the left and top at each gif so I move up for negative top value also move left for negative left value.